- name: Fetch and install binary system updates on FreeBSD hosts
  hosts: all
  become: yes

  tasks:

    - name: Fetch binary system updates
      when: ansible_os_family == "FreeBSD"
      command: freebsd-update --not-running-from-cron fetch
      register: fetch_result
      changed_when: "'No updates needed' not in fetch_result.stdout"

    - name: Get a list of Boot Environments
      when: ansible_facts["os_family"] == "FreeBSD" and ansible_facts["distribution_version"] is version("12", ">=") and fetch_result.changed
      command: bectl list -H
      register: bectl_result
      ignore_errors: yes

    - name: Create a new Boot Environment
      when: bectl_result is not skipped and bectl_result is not failed
      command: bectl create "ansible-{{ansible_date_time.iso8601_basic_short}}"
      register: bectl_result

    - name: Install recently fetched binary system updates
      when: ansible_os_family == "FreeBSD" and fetch_result.changed
      command: freebsd-update --not-running-from-cron install
      register: install_result
      changed_when: "'No updates are available to install' not in install_result.stdout"

    - name: Get new system version and patch level
      when: ansible_os_family == "FreeBSD" and install_result.changed
      command: freebsd-version
      register: version_result
    
    - name: Show update summary
      when: ansible_os_family == "FreeBSD" and version_result.changed
      debug:
        msg: System updated from {{ansible_distribution_release}} to {{version_result.stdout}}
