- name: Upgrade packages on FreeBSD hosts
  hosts: all
  become: yes

  tasks:

    - name: Explicitly update local repository catalogue
      when: ansible_os_family == "FreeBSD"
      command: pkg update
      register: result_update
      changed_when: "'FreeBSD repository update completed' in result_update.stdout"
    # - debug: var=result_update
    #   when: result_update.changed

    - name: Upgrade packages
      when: ansible_os_family == "FreeBSD"
      command: pkg upgrade -y
      register: result_upgrade
      changed_when: "'Your packages are up to date' not in result_upgrade.stdout"
    - debug: var=result_upgrade
      when: result_upgrade.changed
