- name: Upgrade packages on FreeBSD hosts
  hosts: all
  become: yes

  tasks:

    - name: Explicitly update local repository catalogue
      when: ansible_os_family == "FreeBSD"
      command: pkg update
      register: update_result
      changed_when: "'FreeBSD repository update completed' in update_result.stdout"
    
    # - name: Debug the result of Update task
    #   when: update_result.changed
    #   debug:
    #     msg: "{{ update_result.stdout_lines }}"

    - name: Upgrade packages
      when: ansible_os_family == "FreeBSD"
      command: pkg upgrade -y
      register: upgrade_result
      changed_when: "'Your packages are up to date' not in upgrade_result.stdout"

    # - name: Debug the result of Upgrade task
    #   when: upgrade_result.changed
    #   debug:
    #     msg: "{{ upgrade_result.stdout_lines }}"

    - name: List upgraded packages
      when: ansible_os_family == "FreeBSD" and upgrade_result.changed
      debug:
        msg: {{ upgrade_result.stdout_lines | select('search', '] Upgrading') | list }}
