- name: Upgrade packages on FreeBSD hosts
  hosts: all
  become: yes

  tasks:

    - name: Explicitly update local repository catalogue
      when: ansible_os_family == "FreeBSD"
      command: pkg update
      register: update_result
      changed_when: "'FreeBSD repository update completed' in update_result.stdout"
    # - debug: var=update_result
    #   when: update_result.changed

    - name: Upgrade packages
      when: ansible_os_family == "FreeBSD"
      command: pkg upgrade -y
      register: upgrade_result
      changed_when: "'Your packages are up to date' not in upgrade_result.stdout"
    - debug: var=upgrade_result
      when: upgrade_result.changed
