- name: Fetch and install binary system updates on FreeBSD hosts
  hosts: all
  become: yes

  tasks:

    - name: Fetch binary system updates
      when: ansible_os_family == "FreeBSD"
      command: freebsd-update --not-running-from-cron fetch
      register: fetch_result
      changed_when: "'No updates needed' not in fetch_result.stdout"

    - name: Debug the result of Fetch task
      debug: msg="{{ fetch_result.stdout_lines }}"
      when: fetch_result.changed
 
    - name: Install recently fetched binary system updates
      when: ansible_os_family == "FreeBSD" and fetch_result.changed
      command: freebsd-update --not-running-from-cron install
      register: install_result
      changed_when: "'No updates are available to install' not in install_result.stdout"

    - name: Debug the result of Install task
      debug: msg="{{ install_result.stdout_lines }}"
      when: install_result.changed
